// HADA Command Centre — frontend logic (Operational Visibility release).
// Reads ONLY real data:
//   - /hada-control/snapshot.json  (generated by scripts/control-board-snapshot.py
//     from gh + canonical roadmap Markdown; carries generated_at + provenance)
//   - /hada-api/metrics + /hada-api/healthz (live orchestrator probe)
// Fail-closed: missing/stale/unreachable data is shown as such — never faked healthy.

const SNAP = "/hada-control/snapshot.json";
const API = "/hada-api";
const STALE_SECONDS = 30 * 60; // snapshot older than 30m is flagged stale

const VIEWS = ["overview", "roadmap", "development", "governance", "evidence", "agents", "infrastructure", "docs"];
const TITLES = {
  overview: ["Overview", "Single pane of glass — governed autonomous development"],
  roadmap: ["Roadmap", "Canonical roadmap, parsed from docs/MASTER_ROADMAP.md"],
  development: ["Development", "Branches, PRs, CI, verification state"],
  governance: ["Governance", "Gates, reviewer separation, authority boundary"],
  evidence: ["Evidence", "Bundles, identifiers, provenance, integrity"],
  agents: ["Agents", "Roles, assignments, permitted/prohibited actions"],
  infrastructure: ["Infrastructure", "Services HADA governs or observes (no secrets)"],
  docs: ["Documentation", "Navigable summaries of canonical repository Markdown"],
};

// ---- small DOM helpers ----
const $ = (id) => document.getElementById(id);
function el(html) { const t = document.createElement("template"); t.innerHTML = html.trim(); return t.content.firstChild; }
function esc(s) { return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
function tag(status) {
  const map = { ok: "ok", healthy: "ok", complete: "ok", active: "ok", ready: "ok",
    warn: "warn", blocked: "bad", failing: "bad", failed: "bad", unavailable: "neutral",
    planned: "neutral", review: "warn", draft: "warn", stale: "warn", error: "bad" };
  return "pill " + (map[status] || "neutral");
}
function freshness(iso) {
  if (!iso) return { label: "unknown", cls: "warn" };
  const age = (Date.now() - new Date(iso).getTime()) / 1000;
  if (isNaN(age)) return { label: "unknown", cls: "warn" };
  if (age > STALE_SECONDS) return { label: "STALE " + Math.round(age / 60) + "m ago", cls: "warn" };
  return { label: "fresh " + Math.round(age / 60) + "m ago", cls: "ok" };
}

// ---- view routing ----
function setView(name) {
  VIEWS.forEach((v) => $(v + "-view").classList.toggle("active", v === name));
  document.querySelectorAll(".nav-item").forEach((b) => b.classList.toggle("active", b.dataset.view === name));
  const [t, s] = TITLES[name] || ["", ""];
  $("view-title").textContent = t; $("view-subtitle").textContent = s;
}

document.querySelectorAll(".nav-item").forEach((b) => b.addEventListener("click", () => setView(b.dataset.view)));
$("refresh").addEventListener("click", () => boot());

// ---- data fetch ----
async function getJSON(url) {
  const r = await fetch(url, { cache: "no-store" });
  if (!r.ok) throw new Error(url + " -> " + r.status);
  return r.json();
}
async function getText(url) {
  const r = await fetch(url, { cache: "no-store" });
  if (!r.ok) throw new Error(url + " -> " + r.status);
  return r.text();
}
function parseMetrics(text) {
  const out = {};
  text.split("\n").forEach((l) => {
    if (!l || l.startsWith("#")) return;
    const i = l.indexOf(" "); if (i === -1) return;
    out[l.slice(0, i).split("{")[0].trim()] = l.slice(i + 1).trim();
  });
  return out;
}

// ---- render helpers ----
function notice(title, msg) {
  return `<div class="notice"><strong>${esc(title)}</strong>${esc(msg)}</div>`;
}
function availWrap(section, bodyHtml) {
  if (!section || section.available === false) {
    return notice("Data unavailable", (section && section.reason) || "Source could not be reached. The board never shows this as healthy.");
  }
  return bodyHtml;
}

// ===== OVERVIEW =====
function renderOverview(snap, live) {
  const repo = snap.repository, ci = snap.ci, gov = snap.governance, road = snap.roadmap;
  const openPrs = repo.pull_requests.total_open, draftPrs = repo.pull_requests.total_draft;
  const latest = repo.latest_commit;
  const ciFailing = (ci.recent || []).filter((r) => r.conclusion === "failure").length;
  const phases = road.phases || [];
  const complete = phases.filter((p) => p.status === "complete").length;
  const blocked = phases.filter((p) => p.status === "blocked").length;

  // metric tiles (real)
  $("metric-active").textContent = latest ? latest.sha : "—";
  $("metric-review").textContent = openPrs;
  $("metric-approval").textContent = gov.human_approval_required ? "required" : "—";
  $("metric-failed").textContent = ciFailing;

  // milestone — combine BOTH roadmaps
  const stratM1 = phases.find((p) => p.name === "Phase 1") || phases[0];
  const m1tac = (snap.roadmap_m1 && snap.roadmap_m1.phases) ? snap.roadmap_m1.phases : [];
  const b0 = m1tac.find((p) => /B0/i.test(p.name)) || m1tac.find((p) => /deploy/i.test(p.goal || ""));
  const overallStatus = (b0 && b0.status === "blocked") ? "blocked"
    : (stratM1 ? stratM1.status : "planned");
  $("milestone-title").textContent = stratM1 ? stratM1.title : "Roadmap";
  const ms = overallStatus;
  $("milestone-status").textContent = ms;
  $("milestone-status").className = tag(ms);
  const b0note = b0 ? ` M1 tactical: Phase B0 (deploy) is ${b0.status}.` : "";
  $("milestone-summary").textContent = (stratM1 ? stratM1.summary.slice(0, 160) : "") + b0note;
  $("gate-count").textContent = `${complete}/${phases.length} strategic phases complete · ${blocked} blocked · M1 B0 ${b0 ? b0.status : "n/a"}`;
  $("gate-progress").style.width = Math.round((complete / Math.max(phases.length, 1)) * 100) + "%";

  // role separation (real design)
  renderRoles([
    { role: "Implementation (Party 1)", meta: "isolated workspace" },
    { role: "Adversarial reviewer (Party 2)", meta: "separate model" },
    { role: "External reviewer (Party 3)", meta: gov.reviewers ? gov.reviewers.external.split("(")[1]?.replace(")", "") || "automated" : "automated" },
  ]);

  // live infra line
  if (live && live.ok) {
    setBanner("live", `Live · orchestrator ${live.dbUp ? "DB up" : "DB down"} · queue ${live.qUp ? "up" : "down"} · snapshot ${freshness(snap.generated_at).label}`);
    $("execution-state").textContent = "READY — HEALTHY"; $("execution-state").className = "pill ok";
  } else if (live && live.error) {
    setBanner("error", "Live orchestrator API unreachable: " + live.error);
    $("execution-state").textContent = "INFRA UNREACHABLE"; $("execution-state").className = "pill bad";
  }
}

// ===== ROADMAP =====
function renderRoadmap(snap) {
  const road = snap.roadmap;
  const m1 = snap.roadmap_m1;
  const strat = availWrap(road, road.phases.map((p) => `
    <div class="gate-card">
      <span class="pill ${tag(p.status)}">${esc(p.status)}</span>
      <h3>${esc(p.title)}</h3>
      <p>${esc(p.summary.slice(0, 160))}${p.summary.length > 160 ? "…" : ""}</p>
      <small>evidence: ${p.evidence && p.evidence.length ? esc(p.evidence.join(", ")) : "not linked in this view"}</small>
    </div>`).join(""));
  const m1body = availWrap(m1, `
    <div class="table-wrap"><table>
      <thead><tr><th>Phase</th><th>Goal</th><th>State</th></tr></thead>
      <tbody>${(m1.phases || []).map((p) => `<tr><td>${esc(p.name)}</td><td>${esc(p.goal)}</td><td><span class="pill ${tag(p.status)}">${esc(p.state)}</span></td></tr>`).join("")}</tbody>
    </table></div>
    ${m1.current_release ? `<p style="color:var(--muted);font-size:12px">Current release: <code>${esc(m1.current_release)}</code></p>` : ""}
    ${(m1.guardrails || []).length ? `<p style="color:var(--muted);font-size:12px">Guardrails: ${m1.guardrails.map((g) => esc(g)).join(" ")}</p>` : ""}
  `);
  $("roadmap-list").innerHTML = `
    <section class="panel" style="margin-bottom:14px">
      <div class="panel-header"><div><h2>Strategic roadmap (M0–M8)</h2><p>docs/MASTER_ROADMAP.md</p></div>
      <span class="pill neutral">${road.available ? road.phases.length + " phases" : "unavailable"}</span></div>
      <div class="gate-grid">${strat}</div>
    </section>
    <section class="panel">
      <div class="panel-header"><div><h2>M1 tactical roadmap</h2><p>ROADMAP.md — release appliance</p></div>
      <span class="pill neutral">${m1.available ? m1.phases.length + " phases" : "unavailable"}</span></div>
      ${m1body}
    </section>`;
}

// ===== DEVELOPMENT =====
function renderDevelopment(snap) {
  const repo = snap.repository, ci = snap.ci;
  const prRows = (repo.pull_requests.items || []).map((p) => `
    <tr><td><a href="${esc(p.url)}" target="_blank" rel="noopener">#${p.number}</a></td>
        <td>${esc(p.title)}</td>
        <td><span class="pill ${tag(p.is_draft ? "draft" : (p.state === "OPEN" ? "ok" : "neutral"))}">${p.is_draft ? "draft" : esc(p.state)}</span></td>
        <td>${esc(p.branch)}</td><td>${esc(p.updated_at)}</td></tr>`).join("");
  const ciRows = (ci.recent || []).map((r) => `
    <tr><td><a href="${esc(r.url)}" target="_blank" rel="noopener">#${r.run}</a></td>
        <td><span class="pill ${tag(r.conclusion === "success" ? "ok" : (r.conclusion === "failure" ? "bad" : "neutral"))}">${esc(r.conclusion || r.status)}</span></td>
        <td>${esc(r.branch)}</td><td>${esc(r.created_at)}</td></tr>`).join("");
  $("dev-body").innerHTML = availWrap(repo, `
    <div class="panel" style="margin-bottom:14px">
      <div class="panel-header"><div><h2>Pull requests</h2><p>${repo.pull_requests.total_open} open · ${repo.pull_requests.total_draft} draft</p></div>
      <span class="pill neutral">GitHub</span></div>
      <div class="table-wrap"><table>
        <thead><tr><th>#</th><th>Title</th><th>State</th><th>Branch</th><th>Updated</th></tr></thead>
        <tbody>${prRows || '<tr><td colspan="5">none</td></tr>'}</tbody></table></div>
    </div>
    <div class="panel">
      <div class="panel-header"><div><h2>CI checks</h2><p>Recent workflow runs</p></div>
      <span class="pill neutral">GitHub Actions</span></div>
      <div class="table-wrap"><table>
        <thead><tr><th>Run</th><th>Result</th><th>Branch</th><th>Created</th></tr></thead>
        <tbody>${ciRows || '<tr><td colspan="4">none</td></tr>'}</tbody></table></div>
    </div>
    ${repo.latest_commit ? `<p style="color:var(--muted);font-size:12px">Latest commit: <code>${esc(repo.latest_commit.sha)}</code> ${esc(repo.latest_commit.date)} — ${esc(repo.latest_commit.message)}</p>` : ""}
  `);
}

// ===== GOVERNANCE =====
function renderGovernance(snap) {
  const g = snap.governance;
  const adrRows = (g.adrs || []).map((a) => `<tr><td>${esc(a.id)}</td><td><span class="pill ${tag(a.status === "Accepted" ? "ok" : "neutral")}">${esc(a.status)}</span></td><td><code>${esc(a.path)}</code></td></tr>`).join("");
  $("gov-body").innerHTML = availWrap(g, `
    <div class="panel" style="margin-bottom:14px">
      <div class="panel-header"><div><h2>Authority boundary</h2></div><span class="pill bad">read-only</span></div>
      <p style="color:var(--muted)">${esc(g.authority_boundary)}</p>
      <p style="color:var(--muted)">Human approval required: <strong>${g.human_approval_required}</strong> · Self-approval prohibited: <strong>${g.self_approval_prohibited}</strong></p>
    </div>
    <div class="panel">
      <div class="panel-header"><div><h2>ADRs</h2><p>Architecture decision records</p></div></div>
      <div class="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Path</th></tr></thead>
      <tbody>${adrRows || '<tr><td colspan="3">none</td></tr>'}</tbody></table></div>
    </div>`);
}

// ===== EVIDENCE =====
function renderEvidence(snap) {
  const repo = snap.repository;
  const items = [];
  if (repo.latest_commit) items.push({ k: "Latest commit", v: repo.latest_commit.sha, ts: repo.latest_commit.date, prov: "github" });
  (repo.pull_requests.items || []).forEach((p) => items.push({ k: "PR #" + p.number, v: p.state + (p.is_draft ? " (draft)" : ""), ts: p.updated_at, prov: "github", url: p.url }));
  const rows = items.map((i) => `<tr><td>${esc(i.k)}</td><td>${esc(i.v)}</td><td>${esc(i.ts || "—")}</td><td><code>${esc(i.prov)}</code></td><td>${i.url ? `<a href="${esc(i.url)}" target="_blank" rel="noopener">link</a>` : "n/a"}</td></tr>`).join("");
  $("evidence-body").innerHTML = `
    <div class="panel">
      <div class="panel-header"><div><h2>Evidence bundle</h2><p>Signed, content-addressed evidence is produced by the orchestrator; this view lists commit/PR identifiers with provenance.</p></div>
      <span class="pill neutral">partial</span></div>
      <div class="table-wrap"><table><thead><tr><th>Item</th><th>State</th><th>Timestamp</th><th>Provenance</th><th>Link</th></tr></thead>
      <tbody>${rows}</tbody></table></div>
    <p style="color:var(--muted);font-size:12px">Integrity/signature status: not yet exposed by the v5 orchestrator over HTTP. When the evidence API ships, signature verification will appear here. Unavailable data is never shown as verified.</p>`;
}

// ===== AGENTS =====
function renderAgents(snap) {
  const g = snap.governance;
  const agents = [
    { role: "Supervisor", assign: "orchestrator runtime", last: "probe loop", permit: "monitor, publish outbox", prohibit: "merge, deploy, approve" },
    { role: "Planner", assign: "Party 1 workspace", last: "n/a (not instrumented)", permit: "propose bounded changes", prohibit: "self-approve" },
    { role: "Implementer", assign: "Party 1", last: "n/a", permit: "edit in isolated workspace", prohibit: "touch infra/secrets" },
    { role: "Reviewer", assign: "Party 2 (adversarial)", last: "n/a", permit: "review evidence", prohibit: "merge" },
    { role: "Security reviewer", assign: "Party 2 + guardrails", last: "n/a", permit: "flag findings", prohibit: "silently approve" },
    { role: "Release authority", assign: "human", last: "last approval gate", permit: "merge/deploy", prohibit: "delegated to agent" },
  ];
  $("agents-body").innerHTML = `<div class="panel"><div class="panel-header"><div><h2>Agent roles</h2><p>Current assignment, last activity, permitted/prohibited actions</p></div>
    <span class="pill ${tag("ok")}">designed</span></div>
    <div class="gate-grid">${agents.map((a) => `<div class="gate-card"><h3>${esc(a.role)}</h3>
      <p><strong>Assignment:</strong> ${esc(a.assign)}</p>
      <p><strong>Last activity:</strong> ${esc(a.last)}</p>
      <p style="color:var(--green)">Permitted: ${esc(a.permit)}</p>
      <p style="color:var(--red)">Prohibited: ${esc(a.prohibit)}</p></div>`).join("")}</div></div>`;
}

// ===== INFRASTRUCTURE =====
function renderInfrastructure(snap, live) {
  if (!live || live.error) {
    $("infra-body").innerHTML = notice("Live infrastructure unavailable", "The orchestrator probe (/hada-api/metrics) could not be reached. Service health is not shown as healthy.");
    return;
  }
  const rows = [
    { svc: "orchestrator", health: live.ok ? "healthy" : "unhealthy", note: "probe 9108" },
    { svc: "postgres", health: live.dbUp ? "healthy" : "unhealthy", note: "hada_database_up=" + live.dbUp },
    { svc: "valkey", health: live.qUp ? "healthy" : "unhealthy", note: "hada_queue_up=" + live.qUp },
  ];
  $("infra-body").innerHTML = `
    <div class="panel">
      <div class="panel-header"><div><h2>Service health</h2><p>Live from orchestrator probe (no secrets exposed)</p></div>
      <span class="pill ${tag(live.ok ? "ok" : "bad")}">${live.ok ? "all up" : "degraded"}</span></div>
      <div class="table-wrap"><table><thead><tr><th>Service</th><th>Health</th><th>Signal</th></tr></thead>
      <tbody>${rows.map((r) => `<tr><td>${esc(r.svc)}</td><td><span class="pill ${tag(r.health)}">${esc(r.health)}</span></td><td><code>${esc(r.note)}</code></td></tr>`).join("")}</tbody></table></div>
      <p style="color:var(--muted);font-size:12px">Repository/deployment: candidate v5 (PR #12). Data freshness: live probe, fetched on page load.</p>
    </div>`;
}

// ===== DOCS =====
const DOCS = {
  architecture: { title: "Architecture", summary: "Control-plane design: orchestrator, durable queue (Valkey), Postgres store, outbox publisher, and the Caddy edge. The browser talks only to read-only probe endpoints.", topics: ["Probe server (9108)", "Outbox pattern", "Bubblewrap execution", "Trust boundaries"], source: "docs/architecture.md" },
  security: { title: "Security", summary: "Threat model: non-root runtime, capability dropping, read-only bind paths, egress allow-list (github.com, opencode.ai). Self-approval is prohibited.", topics: ["cap_drop ALL", "egress allow-list", "no self-approval", "residual risk"], source: "docs/security.md" },
  roadmap: { title: "Roadmap", summary: "Milestones M0–M8 with entry gates. M1 (durable orchestrator) complete; M0 governance operative; M2–M8 planned.", topics: ["M0 foundation", "M1 orchestrator", "M2–M8", "Entry gates"], source: "docs/MASTER_ROADMAP.md" },
  "governed-autonomy": { title: "Governed autonomy", summary: "Roles, authority, and stopping conditions. Three parties with human approval as the final gate.", topics: ["Party separation", "Stopping conditions", "Human authority", "RFC"], source: "docs/adr/0002-autonomous-repair-pipeline.md" },
  "durable-orchestrator": { title: "Durable orchestrator", summary: "State, queues, workspaces, and recovery. Outbox ensures published events survive crashes.", topics: ["Durable queue", "Workspaces", "Recovery", "Outbox"], source: "docs/runbooks/AUTONOMOUS_REPAIR.md" },
  "external-review": { title: "External review", summary: "Party 3 independent milestone closure checklist. Automated mode for this deployment.", topics: ["Checklist", "Closure", "Automated mode", "Evidence"], source: "docs/runbooks/AUTONOMOUS_REPAIR.md" },
};
document.querySelectorAll(".doc-card").forEach((c) => c.addEventListener("click", () => openDoc(c.dataset.document)));
$("close-document").addEventListener("click", () => $("document-reader").classList.add("hidden"));
function openDoc(key) {
  const d = DOCS[key]; if (!d) return;
  $("document-kind").textContent = "Summary (not canonical)";
  $("document-title").textContent = d.title;
  $("document-summary").textContent = d.summary;
  $("document-topics").innerHTML = d.topics.map((t) => `<div class="topic">${esc(t)}</div>`).join("");
  $("document-source").textContent = d.source;
  $("document-reader").classList.remove("hidden");
}

function setBanner(state, msg) { const b = $("source-banner"); b.className = "source-banner" + (state ? " " + state : ""); $("source-message").textContent = msg; }
function renderRoles(rows) {
  const e = $("agent-list");
  if (!rows.length) { e.innerHTML = notice("Unreachable", "Role state unavailable."); return; }
  e.innerHTML = rows.map((r) => `<div class="stack-row"><span class="dot"></span><span class="role">${esc(r.role)}</span><span class="meta">${esc(r.meta)}</span></div>`).join("");
}

// ===== boot =====
async function boot() {
  setBanner("", "Loading snapshot + live probe…");
  let snap = null, live = null;
  try { snap = await getJSON(SNAP); }
  catch (e) { setBanner("error", "Snapshot unavailable: " + e.message + " — showing live infra only."); }
  try {
    const [h, m] = await Promise.all([getText("/hada-api/healthz"), getText("/hada-api/metrics")]);
    const mm = parseMetrics(m);
    live = { ok: h.trim() === "ok" && mm["hada_database_up"] === "1" && mm["hada_queue_up"] === "1",
             dbUp: mm["hada_database_up"] === "1", qUp: mm["hada_queue_up"] === "1", error: null };
  } catch (e) { live = { ok: false, error: e.message }; }

  if (!snap) {
    // fail closed: render unavailable notices everywhere
    ["roadmap", "development", "governance", "evidence", "agents"].forEach((v) => {
      const t = $(v + (v === "development" ? "-body" : v === "agents" ? "-body" : v === "infrastructure" ? "-body" : "-list" || v + "-body"));
    });
    $("roadmap-list").innerHTML = notice("Snapshot unavailable", "Cannot load repository snapshot. No data is shown as healthy.");
    $("dev-body").innerHTML = notice("Snapshot unavailable", "Development data could not be loaded.");
    $("gov-body").innerHTML = notice("Snapshot unavailable", "Governance data could not be loaded.");
    $("evidence-body").innerHTML = notice("Snapshot unavailable", "Evidence data could not be loaded.");
    $("agents-body").innerHTML = notice("Snapshot unavailable", "Agent data could not be loaded.");
  } else {
    renderOverview(snap, live);
    renderRoadmap(snap); renderDevelopment(snap); renderGovernance(snap);
    renderEvidence(snap); renderAgents(snap);
    if (!live || live.error) setBanner("error", "Snapshot fresh (" + freshness(snap.generated_at).label + ") but live infra unreachable.");
    else setBanner("live", "Snapshot " + freshness(snap.generated_at).label + " · live infra " + (live.ok ? "healthy" : "degraded"));
  }
  renderInfrastructure(snap, live);
}
boot();
