#!/usr/bin/env bash
#
# HADA M1 Phase B — Executable mocked tests for ssh_sudo_capture (correction 1)
#
# Executes the EXACT remote command string generated by ssh_sudo_capture in
# scripts/run-phase-b-deploy.sh against mocked scenarios:
#   a. successful empty output      -> rc 0, emits NONE
#   b. successful nonempty output   -> rc 0, emits sorted lines
#   c. sudo failure                 -> exact nonzero rc preserved across the
#                                      local tee pipeline; NEVER emits NONE
#   d. Docker failure               -> exact nonzero rc preserved across the
#                                      local tee pipeline; NEVER emits NONE
#
# The mock SSH transport executes the generated remote command string
# locally (bash -c), so the generated command itself is what is under test.
# Both failure cases must remain nonzero AFTER the local tee pipeline.
#
# No contact with hada-control. No Docker required (mocked on PATH).
#
set -Eeuo pipefail

PASS_COUNT=0
FAIL_COUNT=0
TEMP_DIR="$(mktemp -d /tmp/hada-ssc-test-XXXXXX)"
trap 'rm -rf "${TEMP_DIR}"' EXIT

assert_pass() { printf 'PASS: %s\n' "$1"; PASS_COUNT=$((PASS_COUNT + 1)); }
assert_fail() { printf 'FAIL: %s\n' "$1" >&2; FAIL_COUNT=$((FAIL_COUNT + 1)); }

DEPLOY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNNER="${DEPLOY_ROOT}/scripts/run-phase-b-deploy.sh"
[[ -f "${RUNNER}" ]] || { echo "FAIL: runner not found: ${RUNNER}" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Source the runner in test-library mode (functions only, no main, no trap)
# ---------------------------------------------------------------------------
export HADA_PHASE_B_TEST_LIB=1
export HADA_PHASE_B_NO_CLEANUP_TRAP=1
export HADA_PHASE_B_DEPLOY_DIR="${DEPLOY_ROOT}"
export HADA_PHASE_B_EVIDENCE_DIR="${TEMP_DIR}/evidence"
mkdir -p "${HADA_PHASE_B_EVIDENCE_DIR}"
# shellcheck source=../../scripts/run-phase-b-deploy.sh
source "${RUNNER}"

# ---------------------------------------------------------------------------
# Mock SSH transport: execute the generated remote command string locally.
# Records every invocation for inspection.
# ---------------------------------------------------------------------------
MOCK_SSH="${TEMP_DIR}/mock-ssh"
cat > "${MOCK_SSH}" <<'EOF'
#!/usr/bin/env bash
# The runner passes the remote command as the final argument.
cmd="${@: -1}"
# One base64 record per generated command (commands are multi-line).
printf '%s\n' "$(printf '%s' "${cmd}" | base64 -w0)" >> "${HADA_MOCK_SSH_LOG:?}"
exec bash -c "${cmd}"
EOF
chmod +x "${MOCK_SSH}"
export HADA_MOCK_SSH_LOG="${TEMP_DIR}/ssh-commands.log"
: > "${HADA_MOCK_SSH_LOG}"
export HADA_PHASE_B_MOCK_SSH="${MOCK_SSH}"
# Re-point the transport array at the mock (it was set at source time).
SSH_CMD=("${HADA_PHASE_B_MOCK_SSH}")

install_mock_sudo_passthrough() {
    local bin_dir="$1"
    cat > "${bin_dir}/sudo" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ "${1-}" == "-n" ]]; then shift; fi
if [[ "$#" -eq 0 ]]; then echo "sudo: missing command" >&2; exit 1; fi
exec "$@"
EOF
    chmod +x "${bin_dir}/sudo"
}

# ===========================================================================
# Case a: successful EMPTY output -> rc 0, output exactly NONE
# ===========================================================================
MOCK_A="${TEMP_DIR}/mock-a"; mkdir -p "${MOCK_A}"
install_mock_sudo_passthrough "${MOCK_A}"
cat > "${MOCK_A}/docker" <<'EOF'
#!/usr/bin/env bash
if [[ "${1-}" == "ps" && "${2-}" == "-aq" ]]; then exit 0; fi
echo "unexpected docker args: $*" >&2
exit 99
EOF
chmod +x "${MOCK_A}/docker"

set +e
PATH="${MOCK_A}:$PATH" ssh_sudo_capture "case-a-empty" "sudo -n docker ps -aq" >"${TEMP_DIR}/a.stdout" 2>"${TEMP_DIR}/a.stderr"
RC_A=$?
set -e
OUT_A="$(cat "${HADA_PHASE_B_EVIDENCE_DIR}/case-a-empty.txt" 2>/dev/null || true)"

if [[ ${RC_A} -eq 0 && "${OUT_A}" == "NONE" ]]; then
    assert_pass "a: successful empty output -> rc 0 and NONE"
else
    assert_fail "a: empty success (rc=${RC_A}, out='${OUT_A}')"
fi

# ===========================================================================
# Case b: successful NONEMPTY output -> rc 0, sorted output
# ===========================================================================
MOCK_B="${TEMP_DIR}/mock-b"; mkdir -p "${MOCK_B}"
install_mock_sudo_passthrough "${MOCK_B}"
cat > "${MOCK_B}/docker" <<'EOF'
#!/usr/bin/env bash
if [[ "${1-}" == "ps" && "${2-}" == "-aq" ]]; then
  printf '%s\n' 'def456' 'abc123' 'ghi789'
  exit 0
fi
exit 99
EOF
chmod +x "${MOCK_B}/docker"

set +e
PATH="${MOCK_B}:$PATH" ssh_sudo_capture "case-b-nonempty" "sudo -n docker ps -aq" >"${TEMP_DIR}/b.stdout" 2>"${TEMP_DIR}/b.stderr"
RC_B=$?
set -e
OUT_B="$(cat "${HADA_PHASE_B_EVIDENCE_DIR}/case-b-nonempty.txt" 2>/dev/null || true)"
EXPECTED_SORTED=$'abc123\ndef456\nghi789'

if [[ ${RC_B} -eq 0 && "${OUT_B}" == "${EXPECTED_SORTED}" ]]; then
    assert_pass "b: successful nonempty output -> rc 0 and sorted output"
else
    assert_fail "b: nonempty success (rc=${RC_B}, out='${OUT_B}')"
fi

# ===========================================================================
# Case c: SUDO failure -> exact nonzero rc preserved AFTER the local tee
# pipeline; NEVER emits NONE. (docker must not even be reached.)
# ===========================================================================
MOCK_C="${TEMP_DIR}/mock-c"; mkdir -p "${MOCK_C}"
cat > "${MOCK_C}/sudo" <<'EOF'
#!/usr/bin/env bash
echo "sudo: a password is required" >&2
exit 42
EOF
chmod +x "${MOCK_C}/sudo"
cat > "${MOCK_C}/docker" <<'EOF'
#!/usr/bin/env bash
echo "docker must not run in sudo-failure case" >&2
exit 0
EOF
chmod +x "${MOCK_C}/docker"

set +e
PATH="${MOCK_C}:$PATH" ssh_sudo_capture "case-c-sudo-fail" "sudo -n docker ps -aq" >"${TEMP_DIR}/c.stdout" 2>"${TEMP_DIR}/c.stderr"
RC_C=$?
set -e
OUT_C="$(cat "${HADA_PHASE_B_EVIDENCE_DIR}/case-c-sudo-fail.txt" 2>/dev/null || true)"

if [[ ${RC_C} -ne 0 ]]; then
    assert_pass "c: sudo failure stays nonzero after the local tee pipeline (rc=${RC_C})"
else
    assert_fail "c: sudo failure must remain nonzero after tee (got rc=0)"
fi
if [[ ${RC_C} -eq 42 ]]; then
    assert_pass "c: exact sudo failure status (42) preserved through capture"
else
    assert_fail "c: exact status not preserved (expected 42, got ${RC_C})"
fi
if grep -q '^NONE$' <<<"${OUT_C}"; then
    assert_fail "c: failed query must NEVER emit NONE"
else
    assert_pass "c: failed query does not emit NONE"
fi

# ===========================================================================
# Case d: DOCKER failure -> exact nonzero rc preserved AFTER the local tee
# pipeline; NEVER emits NONE.
# ===========================================================================
MOCK_D="${TEMP_DIR}/mock-d"; mkdir -p "${MOCK_D}"
install_mock_sudo_passthrough "${MOCK_D}"
cat > "${MOCK_D}/docker" <<'EOF'
#!/usr/bin/env bash
echo "permission denied while trying to connect to the Docker daemon socket" >&2
exit 17
EOF
chmod +x "${MOCK_D}/docker"

set +e
PATH="${MOCK_D}:$PATH" ssh_sudo_capture "case-d-docker-fail" "sudo -n docker ps -aq" >"${TEMP_DIR}/d.stdout" 2>"${TEMP_DIR}/d.stderr"
RC_D=$?
set -e
OUT_D="$(cat "${HADA_PHASE_B_EVIDENCE_DIR}/case-d-docker-fail.txt" 2>/dev/null || true)"

if [[ ${RC_D} -ne 0 ]]; then
    assert_pass "d: docker failure stays nonzero after the local tee pipeline (rc=${RC_D})"
else
    assert_fail "d: docker failure must remain nonzero after tee (got rc=0)"
fi
if [[ ${RC_D} -eq 17 ]]; then
    assert_pass "d: exact docker failure status (17) preserved through capture"
else
    assert_fail "d: exact status not preserved (expected 17, got ${RC_D})"
fi
if grep -q '^NONE$' <<<"${OUT_D}"; then
    assert_fail "d: failed query must NEVER emit NONE"
else
    assert_pass "d: failed query does not emit NONE"
fi

# ===========================================================================
# Structural assertions on the generated remote command itself
# ===========================================================================
GEN_CMD="$(tail -1 "${HADA_MOCK_SSH_LOG}" | base64 -d)"

# The exact generated remote command must begin with set -Eeuo pipefail
if [[ "${GEN_CMD}" == set\ -Eeuo\ pipefail* ]]; then
    assert_pass "generated remote command begins with 'set -Eeuo pipefail'"
else
    assert_fail "generated remote command does not begin with 'set -Eeuo pipefail'"
fi

# sort must NOT appear inside the docker command substitution $( ... )
# Extract the substitution body and check.
if grep -qE 'out=\$\([^)]*\|\s*sort' <<<"${GEN_CMD}"; then
    assert_fail "sort is still inside the Docker command substitution"
else
    assert_pass "no sort or pipeline inside the Docker command substitution"
fi

# The inner command must not be quoted as one single executable
# (i.e. the substitution is `out=$( sudo -n docker ps -aq )`, not
# `out=$( "sudo -n docker ps -aq" )`).
if grep -qE 'out=\$\([[:space:]]*"sudo' <<<"${GEN_CMD}"; then
    assert_fail "inner command is quoted as a single executable"
else
    assert_pass "inner command is not quoted as a single executable"
fi

# sort runs only after the rc check (rc guard precedes the sort invocation)
rc_line=$(grep -n 'rc != 0' <<<"${GEN_CMD}" | head -1 | cut -d: -f1)
sort_line=$(grep -n '| sort' <<<"${GEN_CMD}" | head -1 | cut -d: -f1)
if [[ -n "${rc_line}" && -n "${sort_line}" && ${rc_line} -lt ${sort_line} ]]; then
    assert_pass "sort occurs only after the success check in generated command"
else
    assert_fail "sort does not occur after the success check (rc_line=${rc_line}, sort_line=${sort_line})"
fi

# Every generated command across all 4 cases began with set -Eeuo pipefail
GEN_COUNT=$(wc -l < "${HADA_MOCK_SSH_LOG}")
PF_COUNT=0
while IFS= read -r rec; do
    if [[ "$(printf '%s' "${rec}" | base64 -d)" == set\ -Eeuo\ pipefail* ]]; then
        PF_COUNT=$((PF_COUNT + 1))
    fi
done < "${HADA_MOCK_SSH_LOG}"
if [[ "${GEN_COUNT}" -eq 4 && "${PF_COUNT}" -eq 4 ]]; then
    assert_pass "all 4 generated remote commands begin with set -Eeuo pipefail"
else
    assert_fail "expected 4 generated commands each with pipefail (cmds=${GEN_COUNT}, pipefail=${PF_COUNT})"
fi

# ---------------------------------------------------------------------------
echo ""
echo "============================================"
echo "ssh_sudo_capture mocked test results"
echo "============================================"
echo "Passed: ${PASS_COUNT}"
echo "Failed: ${FAIL_COUNT}"
echo ""
if [[ ${FAIL_COUNT} -gt 0 ]]; then
    echo "RESULT: FAIL"
    exit 1
fi
echo "RESULT: PASS"
exit 0
